---
dependencies:
  - role: bbg-ssl
    name: "{{ yum_mirror.apache.ssl.name }}"
    ssl_cert: "{{ yum_mirror.apache.ssl.cert }}"
    ssl_key: "{{ yum_mirror.apache.ssl.key }}"
    ssl_intermediate: "{{ yum_mirror.apache.ssl.intermediate }}"
    ssl_ca_cert: ~
    when: yum_mirror.apache.ssl.enabled
    tags: ['bbg-ssl']
  - role: apache
  - role: logging-config
    service: yum_mirror
    logdata: "{{ yum_mirror.logs }}"
    forward_type: "{{ yum_mirror.logging.forwarder }}"
    when: logging.enabled|default("True")|bool
  - role: sensu-check
