---
dependencies:
  - role: bbg-ssl
    name: "{{ file_mirror.apache.ssl.name }}"
    ssl_cert: "{{ file_mirror.apache.ssl.cert }}"
    ssl_key: "{{ file_mirror.apache.ssl.key }}"
    ssl_intermediate: "{{ file_mirror.apache.ssl.intermediate }}"
    ssl_ca_cert: ~
    when: file_mirror.apache.ssl.enabled
    tags: ['bbg-ssl']
  - role: apache
  - role: logging-config
    service: file_mirror
    logdata: "{{ file_mirror.logs }}"
    forward_type: "{{ file_mirror.logging.forwarder }}"
    when: logging.enabled|default("True")|bool
  - role: sensu-check
